auth0:
  domain: https://oumabaros.us.auth0.com
  audience: mern-food-ordering-app-api
  jwk-set-uri: https://oumabaros.us.auth0.com/.well-known/jwks.json
spring:
  application:
    name: restaurant-service
  servlet:
    multipart:
      enabled: true
  profiles:
    active: dev
  config:
    import: "optional:configserver:"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth0.domain}/
          audiences:
            - ${auth0.audience}
          jwk-set-uri: ${auth0.jwk-set-uri}
  cloud:
    config:
      uri: http://config-service:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
      username: user
      password: password
      label: master
  kafka:
    producer:
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: http://kafka:9092,http://kafka:9094
server:
  port: 4000
management:
  endpoints:
    web:
      exposure:
        include: refresh
restaurant:
  greeting: Hey Restaurant Service
logging:
  level:
    root: info
billing:
  service:
    address: http://billing-service
    port: 9001
auth:
  service:
      address: http://auth-service
      port: 9002
cloudinary:
  cloud_name: dwgu3hrk4
  api_key: 759921766696886
  api_secret: wwVhaMApZ9w1dXrHrx2PmRxt0QE




