auth0:
  audience: mern-food-ordering-app-api
  domain: oumabaros.us.auth0.com
  front-end: http://localhost:5173
  client-id: qdHdKxJmRtLyuquwypNeyXVkWhw1rvGB
  client-secret: wljPCTHS-_YxwHrN9nh46GSnG49_4tbtKR3a0ZEbM1nVcDsME82pyzQBSKf9218a
server:
  port: 4005
spring:
  kafka:
    producer:
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: http://kafka:9092,http://kafka:9094
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences:
            - ${auth0.audience}
          issuer-uri: https://${auth0.domain}/
      client:
        registration:
          auth0:
            client-id: ${auth0.client-id}
            client-secret: ${auth0.client-secret}
            scope: openid+profile+email
            redirect-uri: ${auth0.front-end}
        provider:
          auth0:
            issuer-uri: https://${auth0.domain}/

  cloud:
    config:
      uri: http://config-service:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
      username: user
      password: password
      label: master
  application:
    name: auth-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:"
  datasource:
    password: password
    url: jdbc:postgresql://auth-service-db:5432/db
    username: admin_user
  jpa:
      hibernate:
        ddl-auto: update
  sql:
      init:
        mode: always
management:
  endpoints:
    web:
      exposure:
        include: refresh
auth:
  greeting: Hey auth
