auth0:
  jwk-set-uri: https://oumabaros.us.auth0.com/.well-known/jwks.json
server:
  port: 4005
spring:
  kafka:
    producer:
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: http://kafka:9092,http://kafka:9094
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${auth0.jwk-set-uri}
  cloud:
    config:
      uri: http://config-service:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
      username: user
      password: password
      label: master
  application:
    name: auth-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:"
  datasource:
    password: password
    url: jdbc:postgresql://auth-service-db:5432/db
    username: admin_user
  jpa:
      hibernate:
        ddl-auto: update
  sql:
      init:
        mode: always
management:
  endpoints:
    web:
      exposure:
        include: refresh
auth:
  greeting: Hey auth
