server:
  port: 4004 # Gateway listens on port 4004

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173" # Replace with your actual frontend origin(s)
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*" # Or specify specific headers like Content-Type, Authorization
            allowCredentials: true
            maxAge: 3600 # Cache preflight request for 1 hour
        add-to-simple-url-handler-mapping: true # Important for handling OPTIONS preflight requests
      routes:
        - id: auth-service-route
          uri: http://host.docker.internal:4005
          predicates:
            - Path=/api/my/user/**
          filters:
            - StripPrefix=1

        # Route for /api/restaurants/** to restaurant-service
        - id: restaurant-service-route
          uri: http://host.docker.internal:4000
          predicates:
            - Path=/api/my/restaurants/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # Route for /api/docs/restaurants to restaurant-service /v3/api-docs
        - id: api-docs-restaurant-route
          uri: http://host.docker.internal:4000
          predicates:
            - Path=/api-docs/restaurants
          filters:
            - RewritePath=/api-docs/restaurants,/v3/api-docs

        - id: api-docs-auth-route
          uri: http:/host.docker.internal:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs